### ISSUE TITLE
404 Error unable to connect to https://mcmc-monitor-proxy.herokuapp.com

### ISSUE THREAD

**Issue by aryaamgen** [flatironinstitute/mcmc-monitor#108]
I was able to run MCMC monitor fine a couple months ago on a remote computer, but now I'm getting the error below when I try to run it.  I'm able to go to the link  where it says "Connect on remote machine" but then my files don't appear and it says "Not connected to service https://lit-bayou-76056.herokuapp.com".

```
Connecting to https://mcmc-monitor-proxy.herokuapp.com
Error: Unexpected server response: 404
    at ClientRequest.<anonymous> (/data/home/apourzan/node_modules/ws/lib/websocket.js:888:7)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
Websocket error.
Websocket closed.
```

**Comment by jsoules** [comment]
Hi, thanks for the heads up about this--looks like the proxy server is not responding. We'll look into this and let you know once it's fixed.

**Comment by magland** [comment]
I needed to restart the proxy server. But now it's at a slightly different URL. https://mcmc-monitor-proxy-0b1b73a9f2a0.herokuapp.com/

So I needed to update the default proxy url in the mcmc-monitor service, and I published a new version to npm
https://www.npmjs.com/package/mcmc-monitor

@jsoules, In the proecess I needed to disable a couple test files because I was getting a compilation error that I wasn't sure how to fix.

@aryaamgen could you try with the latest version? If it still doesn't work, you may need to manually set the env var MCMC_MONITOR_PROXY to
https://mcmc-monitor-proxy-0b1b73a9f2a0.herokuapp.com/

**Comment by aryaamgen** [comment]
Thanks for the quick response @jsoules and @magland. I just tried downloading the latest version of of MCMC monitor and and setting `MCMC_MONITOR_PROXY`. I'm still getting an error but it look like a 503 error this time not a 404. Here are the exact commands I used below, maybe I did something wrong there? By the way, my nvm version is 0.39.5 and my node version is 16.20.2.

```
$ npm install mcmc-monitor@latest

changed 1 package, and audited 124 packages in 2s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ export MCMC_MONITOR_PROXY=https://mcmc-monitor-proxy-0b1b73a9f2a0.herokuapp.com/
$ echo $MCMC_MONITOR_PROXY
https://mcmc-monitor-proxy-0b1b73a9f2a0.herokuapp.com/
$ npx mcmc-monitor@latest start --dir /path/to/parent/output/directory/of/sampler/ --verbose --enable-remote-access

Connect on local machine: https://flatironinstitute.github.io/mcmc-monitor?s=http://localhost:61542

Connecting to proxy
Server is running on port 61542
Connecting to https://mcmc-monitor-proxy-0b1b73a9f2a0.herokuapp.com/

Connect on remote machine: https://flatironinstitute.github.io/mcmc-monitor?s=https://mcmc-monitor-proxy-0b1b73a9f2a0.herokuapp.com//s/34462df68f09a90c1e91&webrtc=1

Error: Unexpected server response: 503
    at ClientRequest.<anonymous> (/data/home/apourzan/node_modules/ws/lib/websocket.js:888:7)
    at ClientRequest.emit (node:events:513:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:534:22)
    at TLSSocket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
Websocket error.
Websocket closed.
```

**Comment by magland** [comment]
@aryaamgen 
Oops, there was a misconfiguration. Please try now.

**Comment by aryaamgen** [comment]
> export MCMC_MONITOR_PROXY=https://mcmc-monitor-proxy-0b1b73a9f2a0.herokuapp.com/

Thanks @magland! Now I'm able to stay connected and I don't get the errors in the terminal, but when I click the link to "Connect on remote machine:" I still see that the app loads but my files aren't there and there is a message in red that says "Not connected to service https://mcmc-monitor-proxy-0b1b73a9f2a0.herokuapp.com//s/96395dbb3e5abb3ad2ac".

**Comment by magland** [comment]
Hmmm. Maybe try leaving off the trailing slash in the env var?

**Comment by aryaamgen** [comment]
> export MCMC_MONITOR_PROXY=https://mcmc-monitor-proxy-0b1b73a9f2a0.herokuapp.com/

Good call! I'm able to connect when remove the slash manually or when I set the `MCMC_MONITOR_PROXY` envvar to not have the slash.

**Comment by magland** [comment]
Great! I just published a new version that should have the correct proxy server. So ideally you won't need that env var.

**Comment by aryaamgen** [comment]
Awesome! Thanks again for the help and for maintaining the package. MCMC Monitor has saved me and my teammates a lot of time debugging larger models.
