### ISSUE TITLE
Implement consistent chain ordering

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/mcmc-monitor#16]
Chains in tables and charts are displayed in an arbitrary order. This usually starts off as parse order, but deselecting and reselecting a chain inserts the most-recently-selected chain at the end of the list. This causes reorderings of table rows in the "Tables" tab, and changes the Z-axis (overlap) ordering of the chains as displayed in the charts on the "Diagnostics" and "Scatterplots" tabs.

To fix: implement a sorting operation for data before it is returned from cache and/or sort chains (sequences, etc) by key text.

**Comment by magland** [comment]
One place to enforce this could be in the reducer
https://github.com/flatironinstitute/mcmc-monitor/blob/0006ef8c6ef6ec62c1b3ce8f9c435ffe048d692e/src/MCMCMonitorDataManager/MCMCMonitorData.ts#L151-L156

**Comment by jsoules** [comment]
Perfect. I'll want to do the same for the selected variables as well, since it impacts the ordering of the variable segments in the diagnostics tab and the order of the tables in the tables tab.
