### ISSUE TITLE
Consider decaying poll rates for MCMCDataManager iteration

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/mcmc-monitor#18]
The `MCMCDataManager` keeps sequence and stats data up-to-date by polling every second for new changes. However, in the common case where the process being monitored has completed its run, the data won't be changing and there's no need to be recomputing except in response to a UI action.

It might be worth considering introducing a decaying poll rate for cases where there have been no updates since last check. The downside would be that the current design receives UI updates through the same mechanism (they just invalidate XYZ data, which triggers an update on the next poll request) so introducing too much delay here could lead to less-responsive UI behavior. The existing setup is quite elegant so I'm not too keen on making a separate manual mechanism to trigger recomputation.

As with issue #17, this is not presently a performance issue, but could maybe present a scaling challenge in the context of large data sets.

Need to discuss if this is worth pursuing.

**Comment by magland** [comment]
My feeling about this is that we should not address it until it becomes a problem. I think even for hundreds of sequences the amount of processing needed is negligible, since (if I'm not mistaken) it just checks for boolean flags.

**Comment by jsoules** [comment]
Let's mark this one as a "Won't implement" for now, and if we ever encounter a situation where we need to do it, we can reopen then.
