### ISSUE TITLE
Add an "All Chains" histogram

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/mcmc-monitor#22]
This would be parallel to the 'variables' heading in the tables--returning histogram stats across all chains.

**Comment by magland** [comment]
@jsoules What do you mean by "parallel to"? Do you mean located next to horizontally? vertically? Would it display mean? ess? Should it be hidden by default?

![image](https://user-images.githubusercontent.com/3679296/222778575-0094c984-c06b-4ea6-8fec-f1cc50f9f70c.png)

**Comment by jsoules** [comment]
Sorry, that was vague. I just meant "analogous to"--it would still appear on the "Diagnostics" tab.

But looking at it more closely, it seems like this is already present on the "Scatterplots" tab if you do a 2d matrix--so maybe we don't need to add the same visualization to the diagnostics? @wardbrian what do you think?

**Comment by WardBrian** [comment]
I think its useful if they’re visually next to the ones for each chain shown on the main tab, but I didn’t realize that it was visible on the scatter plots tab. Perhaps that’s just me not exploring enough

**Comment by magland** [comment]
Are we thinking that the number of chains is in the dozens? (a histogram with 4 points is not very meaningful)

**Comment by WardBrian** [comment]
I would like the histogram to be concatenating all of the draws, so it would have more points than any of the individual histograms

**Comment by jsoules** [comment]
Resolved by PR #31
