### ISSUE TITLE
`npx mcmc-monitor@latest` infinite update loop

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/mcmc-monitor#28]
Per @wardbrian yesterday. Under his configuration, when new releases of `mcmc-monitor` are pushed to NPM, `npx` no longer runs them correctly until completing a manual update step. Specifically:

```
$ npx mcmc-monitor@latest --help
Need to install the following packages:
    mcmc-monitor@latest
Ok to proceed? (y) y
[update cycle runs]
$ npx mcmc-monitor@latest --help
Need to install the following packages:
    mcmc-monitor@latest
...
```

This cycle can be fixed by running:

```bash
$ npm i mcmc-monitor@latest
```

after which point the `npx` call will execute as expected/intended.

I have not been able to reproduce this on my machine, but it appears to be happening on the cluster as well.

Looking for steps to reproduce, but I'd like to make sure this issue can be addressed as much as possible before soliciting outside-user feedback.

**Comment by jsoules** [comment]
To reproduce on our cluster environment:

- Log in to workstation
- activate modernish node module:
`module load modules/2.1-20230203 modules/2.1-20230222 node-js/18.12.1`
- activate modern npm module:
`module load npm/9.3.1`
- Install mapbox:
`npm install @mapbox/node-pre-gyp`
- `npx mcmc-monitor@latest --help`
- This requests permission to update, goes through update cycle, but does not actually run the newly installed module or persist the installation (rerunning `npx` just repeats the request for installation).

Note that the instructions in the readme ask for mapbox to be installed globally, but this is not possible in the cluster environment, as users will not have permissions to modify the global node installation.

It looks like @wardbrian's issues on his laptop were also related to not having done a global installation first.

I think we need to revise the instructions to note the known issue and provide a workaround (viz, manually install `@latest` before running with `npx`) since we can't guarantee that users will be willing, or even able, to do global node package installations.

**Comment by magland** [comment]
What version of node is running on the cluster? If it's <16 then that's probably the reason it doesn't run.

**Comment by magland** [comment]
Perhaps we should split things into two steps - install, and run. I thought the purpose of npx was eliminate the need for this... but maybe it's not going to work for us.

**Comment by jsoules** [comment]
So this still bothers me, but after several more hours trying to track down what's causing it, I can't figure anything out. I'm going to just close the issue in light of the updated README instructions that advise manual installation.

**Comment by magland** [comment]
Just one comment about manual "installation"... the npx command doesn't really install anything, in the sense that it doesn't make available the "mcmc-monitor" command. On the other hand, `npm install -g mcmc-monitor` does make that command available. The non-global `npm install mcmc-monitor` I think makes a node_modules directory in the current folder (am I mistaken?) which is not desirable side effect. Perhaps the way to go would be to not use the npx command, but instead do:

```bash
npm install -g mcmc-monitor@latest
mcmc-monitor --dir ...
```

**Comment by jsoules** [comment]
Well, part of this is that it's tough to track down just what exactly the `npx` command does. It appears to be just shorthand for `npm exec ...` with a few minor differences, but one observation that I've made is that on my laptop (where `npx ...` consistently works through upgrades), I wind up with a `~/.npm/_npx/[some hash]/` directory with several installed executables--including `mcmc-monitor` which wasn't explicitly installed--while on Brian's laptop & on the cluster, the `~/.npm/_npx/[some-hash-which-is-the-same]/` directory gets created but is empty. My (unconfirmed) suspicion is that this represents caching the downloaded `mcmc-monitor`, though I don't have proof of this.

In any case, global installation with `-g` may not be possible (like on our cluster) or desirable for all users, so I don't think we can rely on it. (In fact, while I haven't gone so far as to tell Brian to do the global install, one clear variable between his setup and mine was that I had done a global install for `@mapbox/node-pre-gyp` and he had done it only locally.) You're correct that non-global installation (without `-g`) creates a `node_modules` folder in the current working directory; maybe we should advise users of this and encourage them to use a wd they're okay with that happening in?

----

Just to not bury the lede here, I suspect that if the user was willing & able to do an `install -g` to begin with, `npx` would subsequently work; but in some environments they can't (and in others they'd rather not) install global packages.

**Comment by magland** [comment]
The prerequisite instructions ask the user to do a global install

```
npm install -g @mapbox/node-pre-gyp
```

So I think it makes sense to give two sets of installation instructions -- one where global install is possible, and the other where it is not.

And isn't it possible to adjust the npm global directory to a place where the user has permission to write?

**Comment by jsoules** [comment]
So it looks like the global installation was a red herring, or at least installing `@mapbox/node-pre-gyp` in a redefined global install directory doesn't fix the `npx` issue.

I tried setting up a user-owned "global" directory on my cluster account, following "Option 2" from here: http://npm.github.io/installation-setup-docs/installing/a-note-on-permissions.html

1. `mkdir ~/fake-npm-global`
2. `npm config set prefix '~/fake-npm-global'`
3. `export PATH="~/fake-npm-global/bin:$PATH"`
4. `mkdir tmp-mcmc-monitor-npm` (Directory to use for local install)
5. `cd tmp-mcmc-monitor-npm`
6. `npm install -g @mapbox/node-pre-gyp`
7. Confirm that this has not been installed in cwd but instead in `~/fake-npm-global` and that `~/fake-npm-global/bin/` now includes a reference to `node-pre-gyp`
8. `npx --verbose mcmc-monitor@latest --help`
9. Confirm this again prompts for installation, but experiences the same error as before.

Given that, I'm not even sure that the ability to do global install is the right way to break up the instructions.

We should call out that doing a manual install will create a `node-modules` folder in the current directory, which might be undesirable.

**Comment by jsoules** [comment]
Updated the readme to point out that doing a local `npm install` command will create a `node_modules` folder in the current working directory, and advise users to make a subdirectory first if they don't want that.
