### ISSUE TITLE
FR: Link to this github repository somewhere in the web UI

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/mcmc-monitor#33]
Useful for reporting issues, checking for updates, etc

**Comment by jsoules** [comment]
Does https://flatironinstitute.github.io/mcmc-monitor/dev/ look like a good solution?

**Comment by WardBrian** [comment]
That box behaves very poorly on small screens (I first opened that link on my phone) but I think that's the right idea yes. I'd personally opt for not being a callout box and being at the bottom of the page rather than the top, but I am Not a designer so feel free to ignore me

**Comment by jsoules** [comment]
Wow, that is really gross on a narrow screen.

I was just looking for something prominent, but if you're cool with it just being a bottom-of-page link, that's even easier, I'll just do that. New draft in a sec.

**Comment by jsoules** [comment]
https://flatironinstitute.github.io/mcmc-monitor/dev/ is the new version, which just has a link in the footer (on the home page and error page).

Do we think it's important to have this on the run page as well? I think I'd rather not since it doesn't really fit in the layout very well.

**Comment by WardBrian** [comment]
No I think just the home page is good. Looks great!
