### ISSUE TITLE
Data refresh should not change the variable selection state

### ISSUE THREAD

**Issue by jsoules** [flatironinstitute/mcmc-monitor#36]
In the current version, clicking "Refresh data" or having it automatically triggered from auto refresh resets the selected list of variables (to `lp__`). The selection state should be preserved across data refreshes.

Confirmed this occurs on at least the Diagnostics tab and the Scatterplots tab.

To confirm fix:

- Navigate to Diagnostics tab
- Select several variables, not limited to `lp__`
- Manually refresh the data, confirm selection state does not change
- Repeat test for automated update
- Repeat test for 3d scatterplot

**Comment by magland** [comment]
Nice catch!

I believe this is due to:

allVariableNames changes whenever chainsForRun changes, and this triggers the calling of the following hook:

https://github.com/flatironinstitute/mcmc-monitor/blob/d09acd5e8c30180f609d02e3757cf8b8b1a2bf3d/src/components/RunControlPanel.tsx#L44-L49

This is a bit tricky. One possible way to handle this:

```typescript
const selectionInitialized = useRef<boolean>(false)

useEffect(() => {
        if (selectionInitialized.current) return
	// start with just lp__ selected
	if (allVariableNames.includes('lp__')) {
		setSelectedVariableNames(['lp__'])
                selectionInitialized.current = true
	}
}, [runId, setSelectedVariableNames, allVariableNames])

useEffect(() => {
  // trigger re-initialization if run ID has changed.
  selectionInitialized.current = false
}, [runId])
```

**Comment by magland** [comment]
But I think the above is a bit buggy since `selectionInitialized.current = false` doesn't actually trigger calling of the useEffect hook. Some more work is needed.

**Comment by jsoules** [comment]
If I do this:

```
    const nameSelector = useCallback((allVariableNames: string[]) => {
        console.log('\tUpdating variable-name-setter')
        if (allVariableNames.includes('lp__')) {
            setSelectedVariableNames(['lp__'])
        }
    }, [setSelectedVariableNames])

    useEffect(() => {
        console.log("Change in allVariableNames.")
    }, [allVariableNames])

	useEffect(() => {
		// start with just lp__ selected
        console.log('Calling hook to update variable names.')
        nameSelector(allVariableNames)
	}, [runId, nameSelector, allVariableNames])
```

I get messages that all three hooks are being called. This suggests to me that a lot of things we expect to be memoized are not actually fixed; I'm particularly troubled by the change in the `nameSelector` callback since that depends only on the `setSelectedVariableNames` member from `useMCMCMonitor`... I'll see if I can figure out more about what this is doing...

**Comment by magland** [comment]
That's strange because I did the following and only saw the allVariableNames being changed (when chains are updated) as expected.

```typescript
        useEffect(() => {
		// start with just lp__ selected
		if (allVariableNames.includes('lp__')) {
			setSelectedVariableNames(['lp__'])
		}
	}, [runId, setSelectedVariableNames, allVariableNames])

	useEffect(() => {
		console.log('--- run ID changed', runId)
	}, [runId])

	useEffect(() => {
		console.log('--- setSelectedVariableNames changed')
	}, [setSelectedVariableNames])

	useEffect(() => {
		console.log('--- allVariableNames changed')
	}, [allVariableNames])
```

**Comment by magland** [comment]
In your example, just because nameSelector() is being called, it doesn't mean that setSelectedVariableNames is changing. It's a callback, not a useEffect.

**Comment by jsoules** [comment]
Right, right, it's a callback. Okay, that at least is a relief.

**Comment by magland** [comment]
@jsoules here's my modified version of the above (in RunControlPanel.tsx) that doesn't have the pitfall. I think this should work

```typescript
const [selectionInitialized, setSelectionInitialized] = useState(false)

useEffect(() => {
    if (selectionInitialized) return
    if (allVariableNames.length === 0) return
    // start with just lp__ selected
    if (allVariableNames.includes('lp__')) {
        setSelectedVariableNames(['lp__'])
    }
    else {
        setSelectedVariableNames([])
    }
    setSelectionInitialized(true)
}, [selectionInitialized, setSelectedVariableNames, allVariableNames])

useEffect(() => {
  // trigger re-initialization if run ID has changed.
  setSelectionInitialized(false)
}, [runId])
```

**Comment by jsoules** [comment]
So after some sleuthing, it looks like this is actually due to a mistake in the server: `ChainFile.ts` was updating the current timestamp on any "successful" read of the underlying CSV file, even if it returned 0 bytes (e.g. because it was reading past the end of the file). As a result, for completed files, the file pointer would move forward by one byte and the last-read timestamp would update. I have fixed this (since it's a bug), but that won't be enough to fix it during live monitoring (when the known chains will actually update). For this I think we actually want to track what the known variable names are; I'm putting something together for that presently.

**Comment by magland** [comment]
@jsoules Looks like we commented simultaneously. Take a look at my snippet, I think it should do the trick.

**Comment by jsoules** [comment]
Checking it out. I think we're on the same page for this.

I currently have:
```typescript
    const [ knownVariableNames, setKnownVariableNames ] = useState<string[]>([])
...
    useEffect(() => {
        const known = new Set(knownVariableNames)
        if (knownVariableNames.length !== allVariableNames.length || allVariableNames.some(n => !(n in known))) {
            setKnownVariableNames(allVariableNames)
        }
    }, [knownVariableNames, allVariableNames])
```
so doing the comparison to see if they're identical rather than relying on tracking the initialization status; it just feels more straightforward to check it directly. But I have to actually run it and check it :)

**Comment by magland** [comment]
I see, yeah I think that would work.
