### ISSUE TITLE
hook dependency problems

### ISSUE THREAD

**Issue by magland** [flatironinstitute/mcmc-monitor#37]
@jsoules I think you may not have the eslint vscode set up the same way that I do. I get a warning of missing dependencies for this section:

https://github.com/flatironinstitute/mcmc-monitor/blob/d09acd5e8c30180f609d02e3757cf8b8b1a2bf3d/src/useMCMCMonitor.ts#L77-L83

Do you see that warning in your vscode?

To resolve this warning:

`defaultInitialDrawExclusionOptions` should be defined outside of the hook function, otherwise it's a different reference each time.

If detectedWarmupIterationCount only depends on data.chains, then it should take data.chains as the argument rather than data

**Comment by jsoules** [comment]
Looks like my eslint somehow got turned off. Thanks.

I'll push a fix for these in a sec.
