### ISSUE TITLE
Improve default views - notes from Andrew

### ISSUE THREAD

**Issue by magland** [flatironinstitute/mcmc-monitor#59]
Andrew wrote

>  For the output, I like the time series.  I don't like the histograms and autocorrelation functions so much, and I'd recommend that they not be included in the default settings.  Also, if we are going to start with the time series, which I like, I'd recommend printing out R-hat right on the graphs.  Also are you plotting all iterations (warmup and saved)?  I'm guessing yes; if so it would be good for the graph to indicate that; also it would be good to be able to click and just show the saved iterations and have the plots rescale (as is, the plots are dominated b the first few iterations being far away from everything).

**Comment by magland** [comment]
I propose that we make a new tab called "Hist" and move all histograms there.

Also we can make a new tab called "ACF" and move the autocorrelation functions there.

That way they don't clutter the main view.

I suppose we should open separate issues for:

Print R-hat on the graphs

Figure out how to have the plots rescale when the warm-up iterations are excluded. "plots are dominated by the first few iterations being far away from everything"

**Comment by jsoules** [comment]
Split this issue into a few more atomic ones.
