### ISSUE TITLE
scrolling issue on tables tab

### ISSUE THREAD

**Issue by magland** [flatironinstitute/mcmc-monitor#67]
When viewing a lot of variables, the tables view does not scroll all the way to the bottom.

For example,

https://flatironinstitute.github.io/mcmc-monitor/?s=https://mcmc-monitor-proxy.herokuapp.com/s/c76d31a29d3d08e9a536&webrtc=1#/run/tu6mnkcp

Try selecting a bunch of variables and then try scrolling to bottom of tables view. The display is cut off.

**Comment by jsoules** [comment]
Looks good to me.
