### ISSUE TITLE
Estimates flash blank briefly during updates

### ISSUE THREAD

**Issue by WardBrian** [flatironinstitute/mcmc-monitor#8]
When in auto-refresh mode, it seems like the estimates disappear when new data is loaded. 

Is it possible to have it so the previous value is still displayed until the new one is calculated to avoid this?

I've attached here a brief video showing this in the tables tab, but I've also noticed it for the ACF plots.

[Screencast from 02-14-2023 05:04:09 PM.webm](https://user-images.githubusercontent.com/31640292/218873786-1e6ee838-1841-4a1c-8252-9d72a55fb200.webm)

**Comment by magland** [comment]
@jsoules 

The reason this is happening is that the mechanism used for signaling that new stats need to be calculated is to clear out the old stats in the global state (MCMCMonitorContext). This could be improved by creating a new field in the state called something like `updateRequired: boolean` which would be used to signal to the MCMCMonitorDataManager that the stats need updating, without clearing out the old data.

The global state has three entities that are affected by real-time updates: sequences, sequenceStats, and variableStats. See:

https://github.com/flatironinstitute/mcmc-monitor/blob/c4a0db997f6f14983920df022199475444ce7101/src/MCMCMonitorDataManager/MCMCMonitorData.ts#L26-L39

The sequences already has an updateRequested field (a sequence is a sequence of data specific to a chain and a variable)

Here are the places where the sequenceStats and variableStats get invalidated:

https://github.com/flatironinstitute/mcmc-monitor/blob/c4a0db997f6f14983920df022199475444ce7101/src/MCMCMonitorDataManager/MCMCMonitorData.ts#L178-L185

https://github.com/flatironinstitute/mcmc-monitor/blob/c4a0db997f6f14983920df022199475444ce7101/src/MCMCMonitorDataManager/MCMCMonitorData.ts#L245-L250

These could be replaced by setting the updateRequired field (or whatever we call it) to true.

Then in updateSequenceStats.ts this condition could be replaced by checking that field:

https://github.com/flatironinstitute/mcmc-monitor/blob/c4a0db997f6f14983920df022199475444ce7101/src/MCMCMonitorDataManager/updateSequenceStats.ts#L12

Similar for updateVariableStats.ts

**Comment by jsoules** [comment]
(Fixed by PR #19)
