### ISSUE TITLE
Renaming tabs

### ISSUE THREAD

**Issue by magland** [flatironinstitute/mcmc-monitor#87]
Some comments from Bob

>> I find the tab label "Tables" confusing
>> because it doesn't say what it is, whereas the other tabs say what's
>> behind them.  If this is just redundant with other graphical stuff,
>> move it to the end or drop altogether.  If not, figure out a label for
>> it.  I would replace "Time Series" as a label with "Traceplots".
>> There's no "time" involved in these Markov chains and "traceplot" is
>> more descriptive.

**Comment by jsoules** [comment]
`Time Series` -> `Traceplots` no problem

I wouldn't want to drop the tabular data entirely as it's the most performant view & the most quantitative, and offers easy access to traditional evaluation values. Would "Summary Statistics" be an appropriate (& appropriately informative) title?

@bob-carpenter

**Comment by bob-carpenter** [comment]
"Summary statistics" is good.  I was only objecting to the title "Tables," which tells me the form, but not the content.
