### ISSUE TITLE
scatterplots vs scatterplots matrix

### ISSUE THREAD

**Issue by magland** [flatironinstitute/mcmc-monitor#91]
From Bob:

>> What's the difference between scatterplots and scatterplots matrix?
>> For me, it just changes sizes.

I guess we should make this more clear.

**Comment by jsoules** [comment]
Yeah... it took me a minute to figure it out myself at first, and the difference can be pretty subtle for a small number of selections/with the right window sizes.

I guess I'll put ~an info dot graphic with a hover-text explanation~ a tooltip?
