### ISSUE TITLE
need instructions on troubleshooting installation.

### ISSUE THREAD

**Issue by mitzimorris** [flatironinstitute/mcmc-monitor#96]
on a MacBook Air, intel hw, OS Monterey, I was able to install the node.js modules (via sudo) and start the service, but cannot view the output of a local run.

bash console:

```
~/github/zmorris/2023_stancon_workflow/runs (main)> npx mcmc-monitor@latest start --dir ./air_simple --verbose

Connect on local machine: https://flatironinstitute.github.io/mcmc-monitor?s=http://localhost:61542

Server is running on port 61542
 getRuns
 getRuns
 getRuns
```

- each `getRuns` is triggered by web browser request
```
https://flatironinstitute.github.io/mcmc-monitor/?s=http://localhost:61542
```

this is per the readme.

it would be helpful to have an example of how to monitor the output of a local run.

also, signing up for the Heroku app is quite involved - you need to install the Salesforce 2FA app (Authy didn't seem to work here) just to access your account.  as I don't understand much about this proxy service, I didn't pursue this option.   again, it would be useful to explain why one would want to do this instead of letting Flatiron run the proxy.

update:  I realized my error - I needed to specify "--dir .", the parent directory of my output runs.   the monitor is beautiful.  more information on where the output directories are, also explain that in CmdStanPy and CmdStanR it is necessary to specify arg "output_dir" to the sample command (because tmp dirs are hard to find).

**Comment by magland** [comment]
Hi @mitzimorris,

Glad you got that working.

Regarding heroku/proxy ... yeah it's best to just use the flatiron hosted proxy. The heroku instructions are just in there for completeness of the docs... and if somebody starts using this for a lot of traffic, then we might ask them to host their own proxy.

@jsoules let's clarify the docs as suggested.

**Comment by jsoules** [comment]
Hi @mitzimorris,
Thanks! Glad you're finding it useful.

To make sure I understand: the issue we should clarify is that the output directory has to be specified when using `CmdStanPy` / `CmdStanR` because by default it's a `tmp` directory somewhere?

I'm putting up a PR with the revised instructions & will ask for your feedback on it to make sure the changes would've made it clearer.

**Comment by mitzimorris** [comment]
> To make sure I understand: the issue we should clarify is that the output directory has to be specified when using CmdStanPy / CmdStanR because by default it's a tmp directory somewhere?

clarify:
 * what the default directory is
 * what is displayed on the interface - i.e, the clickable links are the subdirectories which contain a set of CSV files.
 
is it possible to navigate through a set of nested directories?  it seems that at the point the monitor is started, the directory specified is fixed.  therefore it's on the user to make sure that outputs go to (nicely named) directories under it.  is this correct?

both CmdStanPy and CmdStanR have ways of inspecting the name of the tmp dir, which is session-specific.  so finding a smooth workflow for monitor + a CmdStanPy and CmdStanR needs to be well-documented, at the least, or made easier in the software.   I would be more than happy to help with the documentation.
